// This file is auto-generated by run "npm run gen:index"; DO NOT EDIT.
export { default as AmtData404NotFound } from './lt-404-not-found.json';
export { default as AmtDataComingSoon } from './lt-coming-soon.json';
