// This file is auto-generated by run "npm run gen-assets"; DO NOT EDIT.

export { default as Lottie404NotFound } from './404-not-found.json';
export { default as LottieComingSoon } from './coming-soon.json';
