// This file is auto-generated by run "npm run gen:index"; DO NOT EDIT.
export { default as IconFlagUk24 } from './i-flag-uk-24.svg';
export { default as IconFlagVn24 } from './i-flag-vn-24.svg';
export { default as IconLogoDark36 } from './i-logo-dark-36.svg';
export { default as IconLogoLight36 } from './i-logo-light-36.svg';
export { default as IconMomo24 } from './i-momo-24.svg';
