// This file is auto-generated by run "npm run gen-assets"; DO NOT EDIT.

export { default as IconLogoDark36 } from './i-logo-dark-36.svg';
export { default as IconLogoLight36 } from './i-logo-light-36.svg';
export { default as IconMomo24 } from './i-momo-24.svg';
